# Schema for the configuration files of the bestreply module.

bestreply.settings:
  type: config_object
  label: 'Best reply settings'
  mapping:
    name:
      type: string
      label: 'The name you wish to use for bestreply'
    change:
      type: integer
      label: 'Show the change bestreply link, when a bestreply already exists'
    types:
      type: sequence
      label: 'Node types you want to mark a comment'
      sequence:
        type: string
        label: 'Node types you want to mark a comment'
